// src/main/java/com/example/urlshortener/model/UrlMapping.java

package com.example.urlshortener.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import java.time.LocalDateTime;

/**
 * Represents the core JPA entity for a URL mapping.
 * Each instance of this class corresponds to a row in the 'url_mapping' table.
 */
@Entity
public class UrlMapping {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Lob // Specifies that this should be mapped to a Large Object type in the DB.
    @Column(nullable = false, length = 2048) // A URL must not be null.
    private String originalUrl;

    @Column(unique = true) // Each short code must be unique.
    private String shortCode;

    @Column(nullable = false)
    private LocalDateTime creationDate;

    private long clickCount;

    // --- NEWLY ADDED FIELD START ---

    /**
     * The timestamp indicating when this short link should expire and no longer be active.
     * This field is nullable. A 'null' value signifies that the link does not have an expiration date
     * and should be considered permanent.
     *
     * When the application starts, Spring Data JPA (via Hibernate) will see this new field
     * and, if your 'spring.jpa.hibernate.ddl-auto' property is set to 'update', it will
     * automatically add an 'expiration_date' column to your 'url_mapping' database table.
     */
    private LocalDateTime expirationDate;

    // --- NEWLY ADDED FIELD END ---

    // Getters and Setters (generated by Lombok or manually created)
    // IMPORTANT: Make sure you have a getter and setter for the new 'expirationDate' field.
    // If you are using Lombok's @Data, @Getter, and @Setter, this will be handled automatically.

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOriginalUrl() {
        return originalUrl;
    }

    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }

    public String getShortCode() {
        return shortCode;
    }

    public void setShortCode(String shortCode) {
        this.shortCode = shortCode;
    }

    public LocalDateTime getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(LocalDateTime creationDate) {
        this.creationDate = creationDate;
    }

    public long getClickCount() {
        return clickCount;
    }

    public void setClickCount(long clickCount) {
        this.clickCount = clickCount;
    }

    public LocalDateTime getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(LocalDateTime expirationDate) {
        this.expirationDate = expirationDate;
    }
}